muesli/termenv

- ansicolors.go
> add ANSI color name constants

- termenv_unix.go
In certain situations, the read of the terminal fd will fail, returning
an EINTR on Darwin. This causes the status report to be printed to
stdout, since the read never occurs.
Similar to issue https://github.com/golang/go/issues/22838
Fixes: #12
> fix: retry sysSelect in Darwin on EINTR

- go.mod
- go.sum
My IDE found an unused dependency while fixing builds on solaris, so I figured I would PR that as well, maybe it's helpful.
> Remove not used dependency from go.mod

- README.md
Fix TemplateFuncs example in `README.md`
> Fix TemplateFuncs example

- color.go
- color_test.go
- termenv_unix.go
> Query fg/bg color with ST terminator

- .github/workflows/build.yml
- .github/workflows/coverage.yml
Also simplifies Go version selection.
> Split up build and coverage workflows

- README.md
- screen.go
Adds missing screen/mouse helper functions.
> Add missing functions to README and update godoc

- README.md
> Fix goreportcard badge

- README.md
Add a footnote for vte-based terminals.
> Group vte-based terminals in README

- README.md
Added a few links to related projects and users of termenv.
> Add links to related projects

- termenv_windows.go
Thanks to @Delta456 for the inspiration!
> Add Windows color support detection

- screen.go
> Fix DisableMousePress doing the opposite

- go.mod
- go.sum
this should fix build on windows/arm64  
refs https://github.com/mattn/go-isatty/pull/71
> feat: update x/sys

- termenv_other.go
Adds shims for AIX and Plan9 platforms.
> fix: shims for AIX and Plan9

- termenv_unix.go
> Properly support tmux in termStatusReport

- examples/ssh/main.go
> fix: update ssh example to use tty instead of pty

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/lint-soft.yml
- .github/workflows/lint.yml
> chore: bump GitHub Action versions

- templatehelper.go
> feat: conveniently access an Output's template func map

- README.md
Split up feature matrix and put it behind a detail tag.
> docs: put feature matrix in a detail tag

- README.md
- examples/hello-world/main.go
- notification.go
Thanks for pointing this out, @maaslalani!
> chore: rename to Notify for consistency

- README.md
- copy.go
Add copy to primary clipboard method.
> Copy to primary clipboard
