style.go

The rest of the necessary checks were already in place; looks like this last part just slipped through.

Fix nil pointer panic when user passes the empty string as a color value

---

examples/hello-world/main.go
termenv_darwin.go
termenv_linux.go
termenv_unix.go

On Darwin, the ioctl syscall requires the `TIOCGETA` and `TIOCSETA`
constants. The Google termios library has the Linux constants
hard-coded, so this fix reimplements some functions for Darwin.
This fixes the dark background check in OS X Terminal.

Darwin specific implementation for term status

---

color.go

Previously, converting #ffffff to Ansi would return 7
(#c0c0c0) instead of 15 (#ffffff). This is because not all of the
ANSIColor ids from 0-15 were checked due to a missing `=` in the loop.

fix: add missing color to ansi256ToANSIColor

---

termenv.go
termenv_test.go

Add `EnvNoColor` and `EnvColorProfile` functions in order to
support color configuration via environment variables:
-   NO_COLOR: https://no-color.org/
-   CLICOLOR/CLICOLOR_FORCE: https://bixense.com/clicolors/
Fixes: #2

feature: add EnvNoColor and EnvColorProfile

---

constants_solaris.go
constants_unix.go

Quick fix to enable building on solaris/illumos based systems

Enable builds on solaris/illumos

---

README.md
color.go
termenv_test.go

Sadly, all the different color types can make naming a bit confusing. This is the best I could come up with, without breaking existing API.

Add Profile.FromColor to convert a color.Color interface to a termenv.Color

---

termenv_unix.go

As discussed in #27, screen/tmux sessions prevent us from executing
terminal status reports reliably. This change detects whether we're
running in such a session and prevents the report from being queried.
This in turn will make termenv rely on environment variables for
foreground/background detection.

Detect screen/tmux sessions

---

termenv_unix.go

Queries to the terminal are sent and the response is read with a timeout of 100ms. If the latency between the program (running on a remote server) and the terminal (running on a user's workstation) is larger than 100ms, this fails and the program may be finished when the response can finally be read.
This commit replaces the timeout-based approach. Two queries are sent to the terminal: first, the query we're interested in, but which may not be supported by the terminal. If it isn't, the terminal will silently ignore the request and not respond at all.
Next, a cursor position query is sent. This should be supported by all terminals.
Then a response is read without a timeout. Either the terminal responds with the cursor position, then we know it does not support the OSC query and we can …

Reliably query terminal on high latency connections

---

color.go
color_test.go
termenv_unix.go

Tested with konsole, gnome-terminal, rxvt, kitty, Hyper, iTerm2, Apple Terminal, ...

Support backslash-less report termination, as used by rxvt

---

screen.go

This PR adds explicit constants for the possible values in `const EraseLineSeq = "%dK"` to aid in readability. The values are:
|Sequence|Result|
|-|-|
|CSI + `0K`|Clear line right of cursor|
|CSI + `1K`|Clear line left of cursor|
|CSI + `2K`|Clear entire line|
Functions have also been added to clear to the left and right of the cursor when working with stdout.

Add explicit constants and functions for clearing lines

---

color.go
examples/hello-world/main.go

In this PR, I implemented the `Stringer` interface for `ANSIColor` and `ANSI256Color`.

Implement the Stringer interface for ansi color types

---

termenv_js.go

Supports GOOS=js GOARCH=wasm go build

termenv: add shim for js

---

termenv.go

As discussed on https://github.com/minio/mc/issues/3938:
OSC queries on CIs like CircleCI get completely ignored and we get stuck in an uncancelable `Read`. This change checks for the presence of a `CI` environment variable and assumes the terminal isn't capable of responding to such queries.

Don't run OSC queries on CI

---

README.md
screen.go
termenv.go

- SetWindowTitle(title)
- SetForegroundColor(color)
- SetBackgroundColor(color)
- SetCursorColor(color)
- SaveScreen
- RestoreScreen

Add session commands

---

README.md
ansi_compat.md

Document which features are supported where.

Add terminal compatbility list to README

---

termenv_unix.go

(u)rxvt and others set three values here: `<foreground>;<alternative-foreground>;<background>`. We're only interested in the first and last value.

Correctly parse COLORFGBG with three values

---

README.md

muxers can't support color querying. Add a footnote why.

Add footnote about terminal multiplexers

---

termenv_unix.go

`ansi` being an option for macOS Terminal, `kitty` sometimes comes without a `COLORTERM` env var being set.

Add 'kitty' and 'ansi' values as a fallback color support detection

---

.github/workflows/lint-soft.yml
.golangci-soft.yml
.golangci.yml
ansicolors.go
color.go
screen.go
style.go
termenv.go

Soft-enforced linters only annotate commits.

Add separate sets of hard- and soft-enforced linters

---

README.md
termenv_windows.go

Great, now I can stop copying this code around everywhere :smile:

Add helper to enable virtual terminal processing on Windows

---

README.md

Move example rendering below badges and license to bottom of README.

Reorder README paragraphs

---

termenv_unix.go

If we're in a different process group as the parent process, we're not in control of the terminal and can't use OSC queries.

Don't use OSC queries if we're not in control of the terminal

---

termenv_unix.go

Prevents falling back to Ascii for screen sessions that don't have the underlying terminal appended to the `TERM` env var.

screen sessions should always support ANSI256

---

README.md
ansi_compat.md
screen.go

needed for https://github.com/knz/bubbline
see https://en.wikipedia.org/wiki/Bracketed-paste
cc @muesli

Bracketed paste sequences

---

README.md
examples/color-chart/main.go
examples/hello-world/main.go
termenv_test.go
termenv_unix.go
termenv_windows.go

The existing `EnableWindowsANSIConsole`/`RestoreWindowsConsole` functions have a number of limitations:
* They are only defined when termenv is built on Windows, and so require the user to use build tags, i.e. multiple source files, to control whether or not they are called and are not shown on https://pkg.go.dev/github.com/muesli/termenv by default.
* They are hardcoded to set the console mode of stdout, and so fail if stdout is not a terminal, e.g. when redirecting the output to a file or when run in a Go test.
This commit adds a `EnableVirtualTerminalProcessing` function with a different API (to avoid breaking backwards compatibility) that is safe to call on all platforms, takes an `io.Writer` as an argument (for output flexibility). See the comments in the function for more details. …

Add friendlier Windows set/restore console API

---

templatehelper.go
templatehelper_test.go
testdata/templatehelper.tpl
testdata/templatehelper_ansi.txt
testdata/templatehelper_ansi256.txt
testdata/templatehelper_ascii.txt
testdata/templatehelper_truecolor.txt

If the color profile doesn't support ANSI color codes, then it likely shouldn't support any Style options either. This returns a no-op funcmap from `termenv.TemplateFuncs` when the color profile is `Ascii`.

fix(templatehelper): no styles in Ascii mode

---

README.md
ansi_compat.md
examples/hello-world/main.go
notification.go

Adds support for system notifications via OSC-777.

feat: add OSC-777 support for system notifications

---

color.go
hyperlink.go
notification.go
screen.go
termenv.go
termenv_unix.go

Reduces use of repeated string literals and `fmt.Sprintf`.

chore: use consts for sequences

---

README.md
screen.go

Add SGR and SGR-Pixels mouse support. Other modes are discouraged to use. UTF-8 only works for UTF-8 locales and there is no way to distinguish between previous mouse modes (< 1005). URxvt on the other hand only works in URxvt. Although some terminals support this protocol, they all support the newer SGR protocol.
SGR & SGR-Pixels modes must be enabled with basic terminal modes like cell motion (1002) and all motion (1003).
Reference: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Extended-coordinates
Reference: http://midnight-commander.org/ticket/2662
Reference: https://github.com/xtermjs/xterm.js/issues/1962
Reference: https://gitlab.gnome.org/GNOME/vte/-/issues/155
Reference: https://bugs.gentoo.org/761787

feat(mouse): add extended mouse sequences

---

termenv_other.go

fixed compiling wasm
trying to compile the hello-world to wasm failed: 
```
termenv/examples/hello-world>   GOOS=js GOARCH=wasm go build -o m main.go
../../termenv.go:41:16: output.ColorProfile undefined (type *Output has no field or method ColorProfile)
../../termenv.go:97:9: o.ColorProfile undefined (type *Output has no field or method ColorProfile)
```
also:
`./main.go:10:33: undefined: termenv.EnableVirtualTerminalProcessing
`
after this PR:
it compiles...

fix: compiling js/wasm/plan9/aix failed missing method ColorProfile 

---

output.go
termenv.go
termenv_test.go

Change the default global output.
Add a WithTTY option to assume tty output
Fixes: https://github.com/muesli/termenv/issues/105
Fixes: https://github.com/muesli/termenv/pull/108

Change default output & add WithTTY option

---

.github/workflows/build.yml
go.mod
go.sum

upgrade golang version to 1.17
supersedes: https://github.com/muesli/termenv/pull/115 & https://github.com/muesli/termenv/pull/120

feat(deps): upgrade go version & golang.org/x/sys

---

output.go

Make sure the default output exists before querying the terminal for the color profile.

fix(output): set default tty before querying the terminal

---

termenv_unix.go

Even tho `TERM` and `COLORTERM` aren't properly set, it supports the TrueColor profile.

fix: Cloud Shell supports RGB colors

---

termenv_unix.go

Wezterm supports truecolor.
Usually it sets `TERM` to `xterm-256color`, but you can also set it to `wezterm` and import its [terminfo](https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo) with `tic` (which will then enable all term features in nvim et al)

fix: wezterm is truecolor

---

output.go
screen.go
screen_test.go
termenv.go
termenv_windows.go

Termenv output can be a buffer, ssh session, a file, or anything that
implements the io.Writer interface.
In the case of an ssh session, the std ssh library returns a
io.ReadWriter for ssh sessions and the current Termenv implementation
makes it impossible to read terminal status reports since it expects a
file in return.
In addition, the TTY() function is confusing since it implies that the
returned value is a TTY. Which is not always true until we check that
using the isTTY() function.
Deprecate TTY() in favor of Writer() which simply returns the underlying
writer. The caller then can infer the type of the writer and decide what
to do with it.
This also deprecates parts of commit https://github.com/muesli/termenv/commit/669c9abfb65169a7a146968e38702d3d80327a42 …

fix(output): export output writer 

---

README.md

updated docs to mention hyperlinks are supported in alacritty since [v0.11.0](https://github.com/alacritty/alacritty/releases/v0.11.0)
Fixes #156

docs: update alacritty OSC 8 support documentation

---

screen_test.go
templatehelper_test.go
termenv_test.go

- do not use `io/ioutil` (deprecated)
- use `[strings|bytes]ReplaceAll(x,y)` instead of `[strings|bytes]Replace(x,y,-1)`

fix: do not use ioutil and other fixes

---

.github/workflows/build.yml
go.mod
go.sum
style.go

Uses `uniseg.StringWidth` for performance benefits.

Use `uniseg.StringWidth`

---

constants_zos.go
termenv_posix.go
termenv_unix.go

Enables termenv to be built on z/OS :)
z/OS uses the same constants as `constants_linux.go` but because its selectively built based on filename instead of tags I needed to copy them to `constants_zos.go`

Add support for building on z/OS

---

profile.go

allows to get the profile name, useful for logs/errors.

feat: Profile.Name()

---

ansicolors.go
color.go
profile.go
termenv.go

Fixes godot lint, comments should end in a period.

Fix lint comments (godot)

---

termenv_unix.go

I dig into the src of almost all terms listed [here](https://github.com/termstandard/colors?tab=readme-ov-file#fully-supporting)
most of them set `TERM=xterm-256color COLORTERM=truecolor`, but some set `TERM=<their name>`, in which case we can handle it here.
This helps specially in SSH sessions, as `COLORTERM` is not sent by default.

feat: mark more term as truecolor

---

termenv_unix.go

see https://github.com/charmbracelet/colorprofile/pull/22

feat: rio is truecolor, xterm is ansi
